version: "3.8"  # Compose 파일 포맷 버전

# ┌───────────────────────────────────────────────────────────────
# │ (A) 서비스들이 소속될 네트워크 정의
# └───────────────────────────────────────────────────────────────
networks:
  app-network:
    driver: bridge

# ┌───────────────────────────────────────────────────────────────
# │ (B) 실제 띄울 서비스 정의
# └───────────────────────────────────────────────────────────────
services:

  # ─────────────────────────────────────────────────────────────
  # 1) PostgreSQL 데이터베이스 서비스
  # ─────────────────────────────────────────────────────────────
  postgres:
    image: postgres:15              # 공식 PostgreSQL 15 이미지 사용
    container_name: postgres-db     # 컨테이너 이름을 postgres-db 로 지정
    restart: unless-stopped         # 실패 시 재시작 옵션
    ports:
      - "5432:5432"                 # 호스트 5432 포트 ↔ 컨테이너 5432 포트 연결
    volumes:
      - pgdata:/var/lib/postgresql/data
      # pgdata 라는 이름의 Docker 볼륨을
      # 실제 DB 데이터가 저장되는 컨테이너 내부 경로에 연결
    env_file:
      - .env                        # 같은 디렉터리의 .env 파일에서 POSTGRES_* 값 읽어옴
    networks:
      - app-network                 # 위에서 정의한 네트워크에 연결

  # ─────────────────────────────────────────────────────────────
  # 2) 백엔드 애플리케이션 서비스
  # ─────────────────────────────────────────────────────────────
  app:
    build:
      context: .            # Dockerfile 이 있는 경로
      dockerfile: Dockerfile        # 사용할 Dockerfile 이름
    image: news-scraper-server:latest        # 빌드된 이미지 이름
    container_name: news-scraper-server    # 컨테이너 이름 지정
    restart: unless-stopped
    ports:
      - "3000:3000"                 # 호스트 3000 포트 ↔ 컨테이너 3000 포트
    env_file:
      - .env                        # .env 에 정의된 DATABASE_URL 읽어옴
    depends_on:
      - postgres                    # postgres 컨테이너가 먼저 준비될 때까지 대기
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

# ┌───────────────────────────────────────────────────────────────
# │ (C) 볼륨 정의: postgres 데이터 영속화용
# └───────────────────────────────────────────────────────────────
volumes:
  pgdata: